### ISSUE TITLE
Pillar example needs more documentation

### ISSUE THREAD

**Issue by pitchblack408** [saltstack-formulas/php-formula#133]
I tried using the default pillar example, but php 7.0 doesn't install.  Is it possible to have better documentation?  I can't get this to work.

**Comment by dseira** [comment]
If you are installing php in Ubuntu 16, by default it is installed php version 7. As in the most of the formulas, you can always overwrite the package to install using the ``lookup`` section; for example, to install php 7 in a CentOS using the remi repository (must be installed first) you can do:

```
php:
  ng:
    lookup:
      pkgs:
        php: 'php70'
        fpm: 'php70-php-fpm'
      fpm:
        service: 'php70-php-fpm'
```

If you check the pillar.example you will see this.
