### ISSUE TITLE
Multiple versions on the same host

### ISSUE THREAD

**Issue by kissifrot** [saltstack-formulas/php-formula#138]
Hello,

It seems the "standard" or ng version of this formula doesn't support it, but would it be possible to suport multiple versions of PHP (for instance 7.0 and 7.1) on the same host?

**Comment by johnkeates** [comment]
Not by design no. But if you really would need to do this (why not a LXC, VM, Container or extra server? or fix the damn scripts ;-) ), you could make a meta-state that applies it with one config first and a second config later on. Creating two pillars in two envs and then doing a high state with the first saltenv and the second saltenv later on will get you both.

**Comment by kissifrot** [comment]
Yes that's I did (meta-state), but I thought someone would have found a cleaner version :)

**Comment by arthurlogilab** [comment]
Would you be against having the "php:ng:version" be either a string (one version) or a list of versions to address this issue ?

**Comment by kissifrot** [comment]
Yes that would be nice, and a good addition would be being able to choose which version would be chosen as default (wwhen running on Debian)

**Comment by arthurlogilab** [comment]
I might be working on this soon, can we get an opinion for the maintainers of the formula ? ping @aboe76 @javierbertoli @johnkeates (not sure about this list)

**Comment by javierbertoli** [comment]
It sounds like a good addition to the formula. I think that it can be something like this (trying to keep it backward compatible)?

* `php:ng:version` accepts either a `single version` (string, fallback) or a list of versions.
* the pillar should accept these formats:
```yaml
# Current format
php:
  ng:
    key1:
      key1_sub1: value_sub1
    key2: value2
```
and a new format:
```yaml
# New format
php:
  ng:
    version:           # We accept a list of versions
      - ver1
      - ver2
    key1:
      key1_sub1: fallback_value1_sub1
    key2: fallback_value2

    # We should be able to override specific values
    # for each version, defaulting to those above (like
    # in the old format)
    ver1:
      key1:
        key1_sub1: ver1_value1_sub1
    ver2:
      key2: ver2_value2
```

which would render these values to the states:

```yaml
# Rendered values
php:
    ver1:
      key1:
        key1_sub1: ver1_value1_sub1
      key2: fallback_value2
    ver2:
      key1:
        key1_sub1: fallback_value1_sub1
      key2: ver2_value2
```

wdyt? Too complicated?
