### ISSUE TITLE
Debian 9 -  Package 'php5' has no installation candidate

### ISSUE THREAD

**Issue by bogdanr** [saltstack-formulas/php-formula#148]
The map doesn't account that PHP5 is not in Debian 9 anymore thus this error is produced:

```
          ID: php
    Function: pkg.installed
        Name: php5
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:
              
              errors:
                  - Running scope as unit: run-r5900112157714843a8cfd57e485e060b.scope
                    E: Package 'php5' has no installation candidate
     Started: 09:38:29.168245
    Duration: 1633.797 ms
```

I guess one fix would be to have the map treat Debian 9 separately.
