### ISSUE TITLE
Incorrect order in php-fpm.conf

### ISSUE THREAD

**Issue by TaiSHiNet** [saltstack-formulas/php-formula#17]
When doing a state.highstate with the following pillar:

```
php:
  ng:
    fpm:                                                                                                                                                                                                                                                          
      service:                                                                                                                                                                                                                                                    
        enabled: True                                                                                                                                                                                                                                             
        opts:                                                                                                                                                                                                                                                     
          reload: True                                                                                                                                                                                                                                            
      config:                                                                                                                                                                                                                                                     
        ini:                                                                                                                                                                                                                                                      
          opts:
            recurse: True
          settings:
            PHP:
              engine: 'Off'

        conf:
          opts:
            recurse: True
          settings:
            global:
              pid: /var/run/php5-fpm.pid
              error_log: /var/log/php5-fpm.log
              include: /etc/php5/fpm/pool.d/*.conf
```

Settings will be outputted like this:

``` [global]
    error_log = /var/log/php5-fpm.log
    include = /etc/php5/fpm/pool.d
    pid = /var/run/php5-fpm.pid 
```

And will break since include -should- be at the end of the config file
