### ISSUE TITLE
[BUG] session.gc_probability=0 prevents sess_ files from being cleaned up

### ISSUE THREAD

**Issue by alxwr** [saltstack-formulas/php-formula#240]
### Formula commit hash / release tag

PHP 8.3 on FreeBDF

### Versions reports (master & minion)

salt-minion 3006.5 (Sulfur)

### Pillar / config used

```yaml
---
php:
  version: 8.3
```

---

### Describe the bug

```
/tmp/sess_3feb24ddb4cc09b051e3c0f09486b046
/tmp/sess_21728c8ea457439fcefeb886c42063fa
/tmp/sess_a8f17e831566f72c767b3f9880252dcf
/tmp/sess_b7043455a7949dadd95168a68bb6bffd
```

Millions of them.

```
# find /tmp -name 'sess_*' | wc -l
5570964
```

### Steps to reproduce the bug

Leave the formula as it is. Wait.

### Expected behaviour

GC works.

### Attempts to fix the bug

```yaml
---
php:
  version: 8.3
  ini:
    defaults:
      Session:
        session.gc_probability: 1
        session.gc_divisor: 100
```

To really speed things up for testing:

```yaml
---
php:
  version: 8.3
  ini:
    defaults:
      Session:
        session.gc_probability: 1
        session.gc_divisor: 1
        session.gc_maxlifetime: 10
```

Now the number goes steadily down. :-)

```
# find /tmp -name 'sess_*' | wc -l
5118795
# find /tmp -name 'sess_*' | wc -l
4908084
```

### Additional context

https://www.php.net/manual/en/session.configuration.php#ini.session.gc-probability
