### ISSUE TITLE
Changing pillar value php.temp_dir causes install-composer state to fail

### ISSUE THREAD

**Issue by joe-niland** [saltstack-formulas/php-formula#75]
On my machines /tmp is mounted as noexec so running the composer installer in the default location (/tmp) fails. I tried changing this to /var/tmp in my pillar files, however then a different issue occurs:

The system interprets the installer file as bash and you get output like this:

```
----------
          ID: install-composer
    Function: cmd.run
        Name: /var/tmp/installer --filename=composer --install-dir=/usr/local/bin
      Result: False
     Comment: Command "/var/tmp/installer --filename=composer --install-dir=/usr/local/bin" run
     Started: 03:44:52.122608
    Duration: 10.569 ms
     Changes:
              ----------
              pid:
                  21698
              retcode:
                  2
              stderr:
                  /var/tmp/installer: 1: /var/tmp/installer: cannot open ?php: No such file
                  /var/tmp/installer: 3: /var/tmp/installer: /bin: Permission denied
                  /var/tmp/installer: 4: /var/tmp/installer: *: not found
                  /var/tmp/installer: 5: /var/tmp/installer: *: not found
                  /var/tmp/installer: 6: /var/tmp/installer: Syntax error: word unexpected (expecting ")")
              stdout:
```

If I prefix the command with php then it works:

```
install-composer:
  cmd.run:
    - name: php {{ php.temp_dir }}/installer --filename={{ php.composer_bin }} --install-dir={{ php.local_bin }}
    - unless: test -f {{ install_file }}
    - require:
      - file: get-composer
```

It seems the formula should detect when the installer file is not executable.
