### ISSUE TITLE
Error with ng FPM

### ISSUE THREAD

**Issue by tomasfejfar** [saltstack-formulas/php-formula#92]
```
          ID: php_ppa_fpm
    Function: pkgrepo.managed
      Result: False
     Comment: Failed to configure repo 'php_ppa_fpm': E: Type 'php_ppa_fpm' is not known on line 17 in source list /etc/apt/sources.list
              E: The list of sources could not be read.
     Started: 17:13:43.298047
    Duration: 333.854 ms
     Changes:
```

It seems that this line is missing the repo name - which results in adding php_ppa_fpm into `sources.list` (https://github.com/saltstack-formulas/php-formula/blob/master/php/ng/installed.jinja#L38). I think it should be like in nginx formula - https://github.com/mojeskolycz/nginx-formula/blob/master/nginx/ng/pkg.sls#L14

Should I create a PR?
