### ISSUE TITLE
Packages Update After Adding PPA

### ISSUE THREAD

**Issue by kdeberna** [saltstack-formulas/php-formula#93]
I am having an issue when I add in a different PPA in the pillar data to install PHP7.0:

```
php:
  use_ppa: True
  ppa_name: 'ondrej/php'
  ng:
    version: 7.0
...
```

The PPA gets added but `apt-get update` is not run so the php7.0 package isn't found.

I worked around this by adding the update to line 31 of php/ng/installed.jinja:

```
...
- name: apt-add-repository -y ppa:{{ ppa_name }} && apt-get update
...
```

I was also looking at lines 36–48 of php/ng/installed.jinja but adding in `- refresh_db: True` to `pkgrepo.managed` didn't help.

Is there a method I am overlooking that is in the formula already?
